[package]
name = "day_4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.2"
itertools = "0.10.5"
ordermap = "0.4.2"
